name: Deploy Brand Directory

on:
  workflow_dispatch:
    inputs:
      brands_csv_url:
        description: "Google Sheets CSV URL for Brands"
        required: true
        default: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSpYsOV_RtsDGwBTiaFTwPz7uSsRDECKKjO710qo6nsy0ysHz8uygfp-93hPygvMIZMuK2ZlWdqRfSF/pub?gid=0&single=true&output=csv"
      master_csv_url:
        description: "Google Sheets CSV URL for Master Catalog"
        required: true
        default: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRNOvN7fqR_qZsosGC4y3iji3bMdRtCT6v2hgY7543adoEQng-MxIwEkjKLd7DfhuXjOhhlOjf64NUA/pub?gid=0&single=true&output=csv"
      placeholder_thumb:
        description: "Optional placeholder (e.g. /thumbs/_placeholder.webp)"
        required: false
        default: ""
      rebuild_drive_previews:
        description: "Rebuild Drive preview database? (true/false)"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
      rebuild_video_previews:
        description: "Rebuild R2 video preview database? (true/false)"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install
          if [ "${{ inputs.rebuild_drive_previews }}" == "true" ]; then
            npm install googleapis
          fi

      - name: Build data.json (merge + validate + health report)
        env:
          BRANDS_CSV_URL: ${{ inputs.brands_csv_url }}
          MASTER_CSV_URL: ${{ inputs.master_csv_url }}
          PLACEHOLDER_THUMB: ${{ inputs.placeholder_thumb }}
        run: node tools/build-data.mjs

      - name: Build Drive Preview Database
        if: inputs.rebuild_drive_previews == 'true'
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "🚀 Building Drive preview database..."
          node tools/build-drive-previews.mjs
          echo "✅ Preview database build complete"

      - name: Build R2 Video Preview Database
        if: inputs.rebuild_video_previews == 'true'
        env:
          R2_PUBLIC_URL: ${{ secrets.R2_PUBLIC_URL }}
        run: |
          echo "🎬 Building video preview database from R2 CSV..."
          node tools/build-r2-previews.mjs
          echo "✅ Video preview database build complete"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/health.json
            public/data.json

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PAGES_PROJECT }}
          directory: ./public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
